version: "3.2.0"
services:
    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            VIRTUAL_HOST: hotel-luxury.local
        container_name: HOTEL_CRUD_SERVER
        ports:
            - 8080:80
            - "9003:9003"  # Xdebug port for IDE
        volumes:
            - .:/var/www/
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        tty: true
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            SERVICE_NAME: mysql
        container_name: HOTEL_CRUD_DBSERVER
        volumes:
            - ./shared/db_data:/var/lib/mysql
