version: "3.1.0"
services:
    mysql:
        image: mysql:5.7
        tty: true
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            SERVICE_NAME: mysql
        container_name: HOTEL_CRUD_DBSERVER
        volumes:
            - ./shared/db_data:/var/lib/mysql
